### ISSUE TITLE
Migrate to Postgres

### ISSUE THREAD

**Issue by soorajbhaskaran** [soorajbhskrn/neeto-ui-challenge#17]
Sqlite doesn't have UUID support. Wheel uses PostgreSQL.

https://stackoverflow.com/a/47243899

_Originally posted by @yedhink in https://github.com/soorajbhskrn/neeto-ui-challenge/pull/12#discussion_r974137160_

**Comment by yedhink** [comment]
@soorajbhskrn You don't have to mention me in these sub-issues. I am getting a lot of notifications. Rather mention me only in the PR or when you need my inputs.
